apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: network-check-googlecom
spec:
  schedule: "0/1 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: docker
            image: kwaazaar/bashrunner
            args: ["$(APPINSIGHTS_INSTRUMENTATIONKEY)","$(METRIC_KEY)", "$(COMMAND)"]
            env:
            - name: APPINSIGHTS_INSTRUMENTATIONKEY
              value: "yourkey"
            - name: METRIC_KEY
              value: googlecom
            - name: COMMAND
              value: 'nslookup www.google.com'
          restartPolicy: Never # Next run will (may) fix it