apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: network-check-googlecom
  labels:
    app: network-check
spec:
  schedule: "0/1 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      activeDeadlineSeconds: 60 # must complete in x seconds
      template:
        spec:
          containers:
          - name: bashrunner
            image: kwaazaar/bashrunner:latest
            imagePullPolicy: Always
            args: ["$(APPINSIGHTS_INSTRUMENTATIONKEY)","$(METRIC_KEY)", "$(COMMAND)"]
            env:
            - name: APPINSIGHTS_INSTRUMENTATIONKEY
              value: "yourkey"
            - name: METRIC_KEY
              value: googlecom
            - name: COMMAND
              value: "nslookup www.google.com && nc -vz -w 10 www.google.com 443 && curl --connect-timeout 10 -v --silent -o /dev/nul https://www.google.com/"
          restartPolicy: Never # Next run will (may) fix it
